module.exports = [
  ["HDFCBANK", "HDFC Bank Ltd."],
  ["ICICIBANK", "ICICI Bank Ltd."],
  ["RELIANCE", "Reliance Industries Ltd."],
  ["BHARTIARTL", "Bharti Airtel Ltd."],
  ["LT", "Larsen & Toubro Ltd."],
  ["SBIN", "State Bank of India"],
  ["INFY", "Infosys Ltd."],
  ["AXISBANK", "Axis Bank Ltd."],
  ["BAJFINANCE", "Bajaj Finance Ltd."],
  ["M&M", "Mahindra & Mahindra Ltd."],
  ["ADANIENT", "Adani Enterprises Ltd."],
  ["ADANIPORTS", "Adani Ports and Special Economic Zone Ltd."],
  ["APOLLOHOSP", "Apollo Hospitals Enterprise Ltd."],
  ["ASIANPAINT", "Asian Paints Ltd."],
  ["BAJAJ-AUTO", "Bajaj Auto Ltd."],
  ["BAJAJFINSV", "Bajaj Finserv Ltd."],
  ["BEL", "Bharat Electronics Ltd."],
  ["CIPLA", "Cipla Ltd."],
  ["COALINDIA", "Coal India Ltd."],
  ["DRREDDY", "Dr. Reddy's Laboratories Ltd."],
  ["EICHERMOT", "Eicher Motors Ltd."],
  ["ETERNAL", "Eternal Ltd."],
  ["GRASIM", "Grasim Industries Ltd."],
  ["HCLTECH", "HCL Technologies Ltd."],
  ["HDFCLIFE", "HDFC Life Insurance Company Ltd."],
  ["HINDALCO", "Hindalco Industries Ltd."],
  ["HINDUNILVR", "Hindustan Unilever Ltd."],
  ["ITC", "ITC Ltd."],
  ["INDIGO", "InterGlobe Aviation Ltd."],
  ["JSWSTEEL", "JSW Steel Ltd."],
  ["JIOFIN", "Jio Financial Services Ltd."],
  ["KOTAKBANK", "Kotak Mahindra Bank Ltd."],
  ["MARUTI", "Maruti Suzuki India Ltd."],
  ["MAXHEALTH", "Max Healthcare Institute Ltd."],
  ["NTPC", "NTPC Ltd."],
  ["NESTLEIND", "Nestle India Ltd."],
  ["ONGC", "Oil & Natural Gas Corporation Ltd."],
  ["POWERGRID", "Power Grid Corporation of India Ltd."],
  ["SBILIFE", "SBI Life Insurance Company Ltd."],
  ["SHRIRAMFIN", "Shriram Finance Ltd."],
  ["SUNPHARMA", "Sun Pharmaceutical Industries Ltd."],
  ["TCS", "Tata Consultancy Services Ltd."],
  ["TATACONSUM", "Tata Consumer Products Ltd."],
  ["TMPV", "Tata Motors Passenger Vehicles Ltd."],
  ["TATASTEEL", "Tata Steel Ltd."],
  ["TECHM", "Tech Mahindra Ltd."],
  ["TITAN", "Titan Company Ltd."],
  ["TRENT", "Trent Ltd."],
  ["ULTRACEMCO", "UltraTech Cement Ltd."],
  ["WIPRO", "Wipro Ltd."]
];
